main:
  params: [event]
  steps:
    - send_sms:
        call: http.post
        args:
          url: "https://${sys.location}-${sys.project_id}.cloudfunctions.net/send_sms"
          body: ${event}
          headers:
            Content-Type: application/json
    - send_email:
        call: http.post
        args:
          url: "https://${sys.location}-${sys.project_id}.cloudfunctions.net/send_email"
          body: ${event}
          headers:
            Content-Type: application/json